name: what_if
description: What If? is an application that uses AI to create images from text.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Database
  flutter_secure_storage: ^8.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Sate Management
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6

  # Media
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  image: ^4.0.17

  # Helper
  intl: ^0.18.0
  uuid: ^3.0.7
  equatable: ^2.0.5
  collection: ^1.17.1
  path_provider: ^2.0.15
  loading_indicator: ^3.1.1
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  dotted_border: ^2.0.0+3
  url_launcher: ^6.1.11
  logger: ^1.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
